language: clojure
lein: 2.7.1
script:
  - jdk_switcher use oraclejdk7
  - lein with-profile +dev:+1.8:+1.9 test
  - jdk_switcher use oraclejdk8
  - lein with-profile +dev:+1.8:+1.9 test
  - jdk_switcher use openjdk7
  - lein with-profile +dev:+1.8:+1.9 test
deploy:
  provider: script
  script: ./snapshots-deploy.sh
  on:
    branch: master

