language: clojure
lein: 2.7.1
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
script:
  - lein with-profile +dev:+1.8:+1.9 test
jobs:
  include:
    - stage: deploy
      jdk: oraclejdk8
      script: skip
      deploy:
        provider: script
        script: ./snapshots-deploy.sh
        on:
          branch: master
