language: clojure
lein: 2.9.1
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
script:
  - lein with-profile +dev:+1.7:+1.9:+1.10 test
jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script: skip
      deploy:
        provider: script
        script: ./snapshots-deploy.sh
        on:
          branch: master
